# coding=gbk


class StringKeyUtils:
    """该类用于存放所有使用的数据项key"""

    '''项目信息使用的key
    '''
    STR_KEY_ID = 'id'
    STR_KEY_NUMBER = 'number'
    STR_KEY_LANG = 'language'
    STR_KEY_OWNER = 'owner'
    STR_KEY_LANG_OTHER = 'Other'
    STR_KEY_NODE_ID = 'node_id'
    STR_KEY_NAME = 'name'
    STR_KEY_FULL_NAME = 'full_name'
    STR_KEY_DESCRIPTION = 'description'
    STR_KEY_CREATE_AT = 'created_at'
    STR_KEY_UPDATE_AT = 'updated_at'
    STR_KEY_STARGAZERS_COUNT = 'stargazers_count'
    STR_KEY_WATCHERS_COUNT = 'watchers_count'
    STR_KEY_LANGUAGE = 'language'
    STR_KEY_FORKS_COUNT = 'forks_count'
    STR_KEY_SUBSCRIBERS_COUNT = 'subscribers_count'
    STR_KEY_OWNER_LOGIN = 'owner_login'
    STR_KEY_PARENT_FULL_NAME = 'parent_full_name'
    STR_KEY_PARENT = 'parent'

    '''用户信息使用到的key '''
    STR_KEY_LOGIN = 'login'
    STR_KEY_SITE_ADMIN = 'site_admin'
    STR_KEY_TYPE = 'type'
    STR_KEY_EMAIL = 'email'
    STR_KEY_FOLLOWERS_URL = 'followers_url'
    STR_KEY_FOLLOWING_URL = 'following_url'
    STR_KEY_STARRED_URL = 'starred_url'
    STR_KEY_SUBSCRIPTIONS_URL = 'subscriptions_url'
    STR_KEY_ORGANIZATIONS_URL = 'organizations_url'
    STR_KEY_REPOS_URL = 'repos_url'
    STR_KEY_EVENTS_URL = 'events_url'
    STR_KEY_RECEVIED_EVENTS_URL = 'received_events_url'
    STR_KEY_COMPANY = 'company'
    STR_KEY_BLOG = 'blog'
    STR_KEY_LOCATION = 'location'
    STR_KEY_HIREABLE = 'hireable'
    STR_KEY_BIO = 'bio'
    STR_KEY_PUBLIC_REPOS = 'public_repos'
    STR_KEY_PUBLIC_GISTS = 'public_gists'
    STR_KEY_FOLLOWERS = 'followers'
    STR_KEY_FOLLOWING = 'following'

    '''pull request可能会使用到的信息'''
    STR_KEY_STATE = 'state'
    STR_KEY_TITLE = 'title'
    STR_KEY_USER = 'user'
    STR_KEY_BODY = 'body'
    STR_KEY_CLOSED_AT = 'closed_at'
    STR_KEY_MERGED_AT = 'merged_at'
    STR_KEY_MERGE_COMMIT_SHA = 'merge_commit_sha'
    STR_KEY_AUTHOR_ASSOCIATION = 'author_association'
    STR_KEY_MERGED = 'merged'
    STR_KEY_COMMENTS = 'comments'
    STR_KEY_REVIEW_COMMENTS = 'review_comments'
    STR_KEY_COMMITS = 'commits'
    STR_KEY_ADDITIONS = 'additions'
    STR_KEY_DELETIONS = 'deletions'
    STR_KEY_CHANGED_FILES = 'changed_files'
    STR_KEY_HEAD = 'head'
    STR_KEY_BASE = 'base'
    STR_KEY_USER_ID = 'user_id'
    STR_KEY_BASE_LABEL = 'base_label'
    STR_KEY_HEAD_LABEL = 'head_label'
    STR_KEY_REPO_FULL_NAME = 'repo_full_name'

    '''Branch 可能会使用的数据'''
    STR_KEY_LABEL = 'label'
    STR_KEY_REF = 'ref'
    STR_KEY_REPO = 'repo'
    STR_KEY_SHA = 'sha'
    STR_KEY_USER_LOGIN = 'user_login'

    '''review可能会使用放日数据'''
    STR_KEY_PULL_NUMBER = 'pull_number'
    STR_KEY_SUBMITTED_AT = 'submitted_at'
    STR_KEY_COMMIT_ID = 'commit_id'

    '''review comment 可能会用到的数据'''
    STR_KEY_PULL_REQUEST_REVIEW_ID = 'pull_request_review_id'
    STR_KEY_DIFF_HUNK = 'diff_hunk'
    STR_KEY_PATH = 'path'
    STR_KEY_POSITION = 'position'
    STR_KEY_ORIGINAL_POSITION = 'original_position'
    STR_KEY_ORIGINAL_COMMIT_ID = 'original_commit_id'
    STR_KEY_START_LINE = 'start_line'
    STR_KEY_ORIGINAL_START_LINE = 'original_start_line'
    STR_KEY_START_SIDE = 'start_side'
    STR_KEY_LINE = 'line'
    STR_KEY_ORIGINAL_LINE = 'original_line'
    STR_KEY_SIDE = 'side'
    STR_KEY_IN_REPLY_TO_ID = 'in_reply_to_id'

    '''issue comment 可能会使用的数据'''

    '''commit 可能会使用的数据'''
    STR_KEY_COMMIT = 'commit'
    STR_KEY_AUTHOR = 'author'
    STR_KEY_DATE = 'date'
    STR_KEY_AUTHOR_LOGIN = 'author_login'
    STR_KEY_COMMITTER = 'committer'
    STR_KEY_COMMITTER_LOGIN = 'committer_login'
    STR_KEY_COMMIT_AUTHOR_DATE = 'commit_author_date'
    STR_KEY_COMMIT_COMMITTER_DATE = 'commit_committer_date'
    STR_KEY_MESSAGE = 'message'
    STR_KEY_COMMIT_MESSAGE = 'commit_message'
    STR_KEY_COMMENT_COUNT = 'comment_count'
    STR_KEY_COMMIT_COMMENT_COUNT = 'commit_comment_count'
    STR_KEY_STATS = 'stats'
    STR_KEY_STATUS = 'status'  # 一个使用在commit一个使用在file
    STR_KEY_TOTAL = 'total'
    STR_KEY_STATUS_TOTAL = 'status_total'
    STR_KEY_STATUS_ADDITIONS = 'status_additions'
    STR_KEY_STATUS_DELETIONS = 'status_deletions'
    STR_KEY_PARENTS = 'parents'
    STR_KEY_FILES = 'files'

    '''file 可能会使用的数据'''
    STR_KEY_COMMIT_SHA = 'commit_sha'
    STR_KEY_CHANGES = 'changes'
    STR_KEY_FILENAME = 'filename'
    STR_KEY_PATCH = 'patch'

    '''commit relation 可能使用的数据'''
    STR_KEY_CHILD = 'child'
